# Generated by Django 2.2.1 on 2019-07-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20190710_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
